package components.logicgates;

/**
 * As of the current moment, this class only exists so that my secondary methods
 * have something to call for a constructor. The methods below are
 * auto-generated by VS-code to suppress implementation warnings.
 */
public class LogicGates1 extends LogicGatesSecondary {

    @Override
    public void assemble(Operator op, LogicGates first, LogicGates second) {
        throw new UnsupportedOperationException(
                "Unimplemented method 'assemble'");
    }

    @Override
    public Operator disassemble(LogicGates first, LogicGates second) {
        throw new UnsupportedOperationException(
                "Unimplemented method 'disassemble'");
    }

    @Override
    public boolean compute() {
        throw new UnsupportedOperationException(
                "Unimplemented method 'compute'");
    }

    @Override
    public int size() {
        throw new UnsupportedOperationException("Unimplemented method 'size'");
    }

    @Override
    public int height() {
        throw new UnsupportedOperationException(
                "Unimplemented method 'height'");
    }

    @Override
    public void clear() {
        throw new UnsupportedOperationException("Unimplemented method 'clear'");
    }

    @Override
    public LogicGates newInstance() {
        throw new UnsupportedOperationException(
                "Unimplemented method 'newInstance'");
    }

    @Override
    public void transferFrom(LogicGates arg0) {
        throw new UnsupportedOperationException(
                "Unimplemented method 'transferFrom'");
    }

}
